/**
 * authService.js — Authentication service (Firebase Authentication).
 * -----------------------------------------------------------------------------
 * The UI calls this service; it never touches the Firebase SDK directly (that
 * lives in js/firebase/auth.js). This layer:
 *   - exposes a stable, UI-friendly API,
 *   - maps raw Firebase error codes to human messages,
 *   - normalizes the Firebase user into a small identity object.
 *
 * IDENTITY vs ROLE (important):
 *   Firebase Authentication owns IDENTITY only (uid, email, displayName).
 *   This phase does NOT assign or trust roles. The "role" a user arrives with
 *   (which portal they used) is stored separately as an UNVERIFIED hint
 *   (`pendingRole`) purely for redirect/UX. Real roles + permissions will be
 *   assigned by the Node.js + PostgreSQL backend later, keyed by the Firebase
 *   UID, and verified via Firebase ID token on the server. Nothing here should
 *   ever be treated as an authorization decision.
 * -----------------------------------------------------------------------------
 */
import { ROLES, ENV, STORAGE_KEYS } from '../config.js';
import {
  createEmailUser,
  signInEmailUser,
  signInGoogle,
  signOutUser,
  resetPassword,
  setDisplayName,
  watchAuthState,
  applyPersistence,
  getIdToken,
  auth,
  isFirebaseConfigured,
} from '../firebase/auth.js';
import { authedRequest } from './apiClient.js';

/** Key for the UNVERIFIED role hint (UX only — never an auth claim). */
const PENDING_ROLE_KEY = 'cms.pendingRole';

/* ------------------------------------------------------------------ */
/* Error mapping                                                       */
/* ------------------------------------------------------------------ */

/**
 * Translate a Firebase error code into a safe, user-friendly message.
 * Internal details are logged (for developers) but not shown to users.
 */
function friendlyError(error) {
  const code = error?.code || '';
  // Developer-facing log only; never surface raw codes to end users.
  console.debug('[auth] firebase error:', code, error?.message || '');

  const map = {
    'auth/invalid-email': 'Please enter a valid email address.',
    'auth/user-disabled': 'This account has been disabled. Contact your administrator.',
    'auth/user-not-found': 'Invalid email or password.',
    'auth/wrong-password': 'Invalid email or password.',
    'auth/invalid-credential': 'Invalid email or password.',
    'auth/email-already-in-use': 'This email is already registered. Try signing in instead.',
    'auth/weak-password': 'Password is too weak. Use at least 6 characters.',
    'auth/missing-password': 'Please enter your password.',
    'auth/too-many-requests': 'Too many attempts. Please wait a moment and try again.',
    'auth/network-request-failed': 'Network error. Please check your connection and try again.',
    'auth/popup-closed-by-user': 'Google sign-in was cancelled.',
    'auth/cancelled-popup-request': 'Google sign-in was cancelled.',
    'auth/popup-blocked': 'Popup was blocked by the browser. Please allow popups and try again.',
    'auth/operation-not-allowed': 'This sign-in method is not enabled for this project.',
    'auth/unauthorized-domain': 'This domain is not authorized for sign-in. Add it in Firebase Console.',
  };
  return map[code] || 'Something went wrong. Please try again.';
}

/** Guard so we fail gracefully before the config placeholders are filled in. */
function configGuard() {
  if (!isFirebaseConfigured()) {
    return {
      ok: false,
      error:
        'Firebase is not configured yet. Paste your Firebase config into js/firebase/firebase-config.js.',
    };
  }
  return null;
}

/* ------------------------------------------------------------------ */
/* Identity normalization                                              */
/* ------------------------------------------------------------------ */

/** Reduce a Firebase user to the minimal identity the UI needs. */
export function toIdentity(user) {
  if (!user) return null;
  return {
    uid: user.uid, // generated by Firebase, read dynamically — never hard-coded
    email: user.email || '',
    name: user.displayName || (user.email ? user.email.split('@')[0] : 'User'),
    photoURL: user.photoURL || '',
    provider: user.providerData?.[0]?.providerId || 'password',
    emailVerified: user.emailVerified,
  };
}

/* ------------------------------------------------------------------ */
/* Pending role hint (UNVERIFIED, UX-only)                             */
/* ------------------------------------------------------------------ */

export function setPendingRole(role) {
  if (role) sessionStorage.setItem(PENDING_ROLE_KEY, role);
}
export function getPendingRole() {
  return sessionStorage.getItem(PENDING_ROLE_KEY) || null;
}
export function clearPendingRole() {
  sessionStorage.removeItem(PENDING_ROLE_KEY);
}

/* ------------------------------------------------------------------ */
/* Backend profile sync (Firebase identity -> PostgreSQL users)        */
/* ------------------------------------------------------------------ */
/*
 * After Firebase authentication, we exchange the Firebase ID token for the
 * application profile owned by the backend/PostgreSQL. The DB `role` is the
 * source of truth — the portal the user logged in through is NOT trusted.
 *
 * The synced profile is cached in sessionStorage under STORAGE_KEYS.SESSION so
 * portal pages can read the verified role without re-calling the backend on
 * every navigation. This cache is a convenience only; the backend re-verifies
 * the Firebase token on every protected request (real authorization is server
 * side). Manipulating this cache cannot escalate privileges on the server.
 */

/** Persist the backend profile for this browser session. */
function setSessionProfile(profile) {
  try {
    sessionStorage.setItem(STORAGE_KEYS.SESSION, JSON.stringify(profile));
  } catch (e) {
    console.debug('[auth] could not cache session profile', e);
  }
}

/** Read the cached backend profile (or null). */
export function getSessionProfile() {
  try {
    const raw = sessionStorage.getItem(STORAGE_KEYS.SESSION);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

/** Remove the cached backend profile. */
export function clearSessionProfile() {
  sessionStorage.removeItem(STORAGE_KEYS.SESSION);
}

/**
 * Exchange the current Firebase ID token for the PostgreSQL user profile.
 * Calls POST /api/auth/sync with `Authorization: Bearer <token>` and NO body
 * (no role is ever sent). On success caches and returns the backend profile.
 *
 * @param {boolean} [forceRefresh=false] force a fresh Firebase ID token
 * @returns {Promise<{ok:boolean, profile?:object, error?:string, status?:number}>}
 */
export async function syncProfile(forceRefresh = false) {
  if (!ENV.AUTH_USE_BACKEND) {
    // Backend sync disabled — nothing to do (mock-only mode).
    return { ok: false, error: 'Backend auth sync is disabled.' };
  }
  try {
    const token = await getIdToken(forceRefresh);
    if (!token) return { ok: false, error: 'Not authenticated.', status: 401 };

    // No body, no role — the backend derives identity from the verified token
    // and owns the role.
    const res = await authedRequest('/auth/sync', token, { method: 'POST' });
    const profile = res?.user || null;
    if (profile) setSessionProfile(profile);
    return { ok: true, profile };
  } catch (error) {
    console.debug('[auth] profile sync failed:', error?.status, error?.message);
    return { ok: false, error: error?.message || 'Profile sync failed.', status: error?.status };
  }
}

/**
 * Fetch the current backend profile without provisioning (GET /api/auth/me).
 * Returns { ok, profile? , status? }. 404 means no profile exists yet.
 */
export async function fetchMyProfile() {
  if (!ENV.AUTH_USE_BACKEND) return { ok: false, error: 'Backend auth sync is disabled.' };
  try {
    const token = await getIdToken();
    if (!token) return { ok: false, error: 'Not authenticated.', status: 401 };
    const res = await authedRequest('/auth/me', token, { method: 'GET' });
    return { ok: true, profile: res?.user || null };
  } catch (error) {
    return { ok: false, error: error?.message, status: error?.status };
  }
}

/**
 * Fetch the profile-completion status (GET /api/profile/status).
 * @returns {Promise<{ok:boolean, status?:object, error?:string}>}
 *   status = { role, hasStudentProfile, hasFacultyProfile, facultyPending, ... }
 */
export async function fetchProfileStatus() {
  if (!ENV.AUTH_USE_BACKEND) return { ok: false, error: 'Backend auth sync is disabled.' };
  try {
    const token = await getIdToken();
    if (!token) return { ok: false, error: 'Not authenticated.', status: 401 };
    const res = await authedRequest('/profile/status', token, { method: 'GET' });
    return { ok: true, status: res?.status || null };
  } catch (error) {
    return { ok: false, error: error?.message, status: error?.status };
  }
}

/**
 * Save the current user's STUDENT profile (POST /api/students/profile).
 * No role is ever sent. Returns { ok, profile?, error?, status? }.
 * @param {object} data { rollNumber, fullName, mobileNumber, program, branch, semester }
 */
export async function saveStudentProfile(data) {
  if (!ENV.AUTH_USE_BACKEND) return { ok: false, error: 'Backend auth sync is disabled.' };
  try {
    const token = await getIdToken(true);
    if (!token) return { ok: false, error: 'Not authenticated.', status: 401 };
    const res = await authedRequest('/students/profile', token, { method: 'POST', body: data });
    return { ok: true, profile: res?.profile || null };
  } catch (error) {
    return { ok: false, error: error?.message || 'Could not save profile.', status: error?.status };
  }
}

/**
 * Save the current user's FACULTY profile (POST /api/faculty/profile).
 * Saving a faculty profile does NOT grant the faculty role (admin approval
 * required). No role is ever sent. Returns { ok, profile?, facultyPending?, ... }.
 * @param {object} data { fullName, mobileNumber, department, designation }
 */
export async function saveFacultyProfile(data) {
  if (!ENV.AUTH_USE_BACKEND) return { ok: false, error: 'Backend auth sync is disabled.' };
  try {
    const token = await getIdToken(true);
    if (!token) return { ok: false, error: 'Not authenticated.', status: 401 };
    const res = await authedRequest('/faculty/profile', token, { method: 'POST', body: data });
    return { ok: true, profile: res?.profile || null, facultyPending: res?.facultyPending !== false };
  } catch (error) {
    return { ok: false, error: error?.message || 'Could not save profile.', status: error?.status };
  }
}

/* ------------------------------------------------------------------ */
/* Public auth API                                                     */
/* ------------------------------------------------------------------ */

/**
 * Register a new account with email + password.
 * Firebase creates the account and generates the UID automatically.
 * @returns {Promise<{ok:boolean, user?:object, error?:string}>}
 */
export async function registerWithEmail({ name, email, password, remember = true, role }) {
  const blocked = configGuard();
  if (blocked) return blocked;
  try {
    await applyPersistence(remember);
    const cred = await createEmailUser(email.trim(), password);
    if (name) {
      try { await setDisplayName(cred.user, name.trim()); } catch (e) { console.debug('[auth] setDisplayName failed', e); }
    }
    if (role) setPendingRole(role);
    const sync = await syncProfile(true);
    return { ok: true, user: toIdentity(cred.user), profile: sync.profile || null };
  } catch (error) {
    return { ok: false, error: friendlyError(error) };
  }
}

/**
 * Sign in with email + password.
 * @returns {Promise<{ok:boolean, user?:object, profile?:object, error?:string}>}
 */
export async function loginWithEmail({ email, password, remember = false, role }) {
  const blocked = configGuard();
  if (blocked) return blocked;
  try {
    await applyPersistence(remember);
    const cred = await signInEmailUser(email.trim(), password);
    if (role) setPendingRole(role);
    const sync = await syncProfile(true);
    return { ok: true, user: toIdentity(cred.user), profile: sync.profile || null };
  } catch (error) {
    return { ok: false, error: friendlyError(error) };
  }
}

/**
 * Sign in / sign up with Google (popup). New Google users are created in
 * Firebase automatically; existing users simply sign in.
 * @returns {Promise<{ok:boolean, user?:object, error?:string}>}
 */
export async function loginWithGoogle({ remember = true, role } = {}) {
  const blocked = configGuard();
  if (blocked) return blocked;
  try {
    await applyPersistence(remember);
    const cred = await signInGoogle();
    if (role) setPendingRole(role);
    const sync = await syncProfile(true);
    return { ok: true, user: toIdentity(cred.user), profile: sync.profile || null };
  } catch (error) {
    return { ok: false, error: friendlyError(error) };
  }
}

/** Send a password reset email. */
export async function sendPasswordReset(email) {
  const blocked = configGuard();
  if (blocked) return blocked;
  try {
    await resetPassword(email.trim());
    return { ok: true };
  } catch (error) {
    return { ok: false, error: friendlyError(error) };
  }
}

/** Sign out of Firebase and clear the unverified role hint. */
export async function logout() {
  try {
    await signOutUser();
  } catch (e) {
    console.debug('[auth] signOut error', e);
  } finally {
    clearPendingRole();
    clearSessionProfile();
  }
}

/**
 * Current authenticated user as an identity object, or null.
 * Note: right after page load Firebase may not have restored the session yet;
 * prefer listenToAuthState() for reliable gating.
 */
export function getCurrentUser() {
  return toIdentity(auth.currentUser);
}

/**
 * Subscribe to Firebase auth state. Fires once with the restored user (or null)
 * and again on every login/logout. Firebase is the source of truth.
 * @param {(identity:object|null)=>void} callback
 * @returns {Function} unsubscribe
 */
export function listenToAuthState(callback) {
  return watchAuthState((user) => callback(toIdentity(user)));
}

export { ROLES, isFirebaseConfigured };
